/**
 * The next number in a zero-padded reference like CYC-2026-0004.
 *
 * These were generated by counting existing rows and adding one, which is only
 * correct while nothing is ever deleted. Delete CYC-2026-0003 out of four and
 * the count says three, so the next cycle is handed 0004 — a code already in
 * use. The unique index then rejects it and the caller gets an opaque 500 with
 * nothing to suggest the numbering is the problem.
 *
 * Taken from the highest reference actually issued instead. The width is fixed
 * and the numbers are zero-padded, so sorting the text descending gives the
 * largest number, and the tail parses back to it.
 *
 * Not a defence against two requests racing — that needs a sequence in the
 * database — but that is not what has been failing.
 */
export function nextReferenceNumber(lastReference: string | null | undefined, width: number): number {
  if (!lastReference) return 1;
  const tail = lastReference.slice(-width);
  const parsed = Number.parseInt(tail, 10);
  return Number.isFinite(parsed) && parsed > 0 ? parsed + 1 : 1;
}

/** Format a number into a reference's zero-padded tail. */
export function pad(n: number, width: number): string {
  return String(n).padStart(width, '0');
}
